---
- name: Deploy RHEL Web Server
  hosts: localhost
  become: true
  tasks:
    - name: Install httpd
      dnf:
        name: httpd
        state: latest
    - name: Start and Enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Deploy Web Content
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        mode: '0644'
    - name: ALLOW HTTP in firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
    - name: Reload firewalld
      command: firewall-cmd --reload